function addEvent(){}
function removeEvent(){}
function fetchJson(){}
function bind(){}
function removeChildren(){}
function removeElem(){}
function addSubmitFn(){}
function setDirty(){}
function setSubmitted(){}
function addImageLinks(){}