    `guid` binary(24) NOT NULL,  
    `tid` bigint(20) unsigned auto_increment,
	`owner_guid` binary(24) NULL,
    `container_guid` binary(24) NULL,
	`time_created` bigint(20) unsigned NOT NULL,
	`time_updated` bigint(20) unsigned NOT NULL,
    `metadata_json` mediumtext null,
    UNIQUE KEY `guid` (`guid`),
	KEY `owner_guid` (`owner_guid`),
    PRIMARY KEY `tid` (`tid`),
	KEY `container_guid` (`container_guid`),
	KEY `time_created` (`time_created`)