    `guid` binary(24) NOT NULL,  
    `tid` bigint(20) unsigned auto_increment,
	`owner_guid` binary(24) NULL,
    `container_guid` binary(24) NULL,
	`time_created` bigint(20) unsigned NOT NULL,
	`time_updated` bigint(20) unsigned NOT NULL,
    `status` tinyint(4) not null default 1,	
    `metadata_json` text null,
    PRIMARY KEY  (`guid`),
	KEY `owner_guid` (`owner_guid`),
    KEY `tid` (`tid`),
	KEY `container_guid` (`container_guid`),
	KEY `time_created` (`time_created`,`tid`),
	KEY `time_updated` (`time_updated`,`tid`)