#!/bin/sh

APP_NAME="qworkers"
APP_HOME=""
USER_HOME="/var/qworker"
AS_USER="qworker"
PHP_HOME="/usr"
DAEMON="/usr/bin/daemon"

APP_ENV="-i -e HOME=$USER_HOME -e USER=$AS_USER -e USERNAME=$AS_USER"

pidfile="$USER_HOME/$APP_NAME.pid"
daemon_args="--name $APP_NAME --pidfile $pidfile"
daemon_start_args="$APP_ENV --user $AS_USER --stdout=/var/log/$APP_NAME/stdout --stderr=/var/log/$APP_NAME/error --chdir=$APP_HOME"

running() {
  $DAEMON $daemon_args --running
}

# dirs under /var/run can go away between reboots.
for p in /var/run/$APP_NAME /var/log/$APP_NAME $QUEUE_PATH; do
  if [ ! -d $p ]; then
    mkdir -p $p
    chmod 775 $p
    chown $AS_USER $p >/dev/null 2>&1 || true
  fi
done

case "$1" in
  start)
    echo -n "Starting $APP_NAME... "

    if [ ! -r $APP_HOME/scripts/$APP_NAME.php ]; then
      echo "FAIL"
      echo "*** $APP_NAME php missing: $APP_HOME/scripts/$APP_NAME.php - not starting"
      exit 1
    fi
    if [ ! -x $PHP_HOME/bin/php ]; then
      echo "FAIL"
      echo "*** $PHP_HOME/bin/php doesn't exist"
      exit 1
    fi
    if running; then
      echo "already running."
      exit 0
    fi
    
    $DAEMON $daemon_args $daemon_start_args -- ${PHP_HOME}/bin/php ${APP_HOME}/scripts/${APP_NAME}.php
    tries=0
    while ! running; do
      tries=$((tries + 1))
      if [ $tries -ge 5 ]; then
        echo "FAIL"
        exit 1
      fi
      sleep 1
    done
    echo "done."
  ;;

  stop)
    echo -n "Stopping $APP_NAME... "
    if ! running; then
      echo "wasn't running."
      exit 0
    fi
    
    pid=`cat $pidfile`
    echo "pid is $pid"
    kill $pid    

    tries=0
    while running; do
      tries=$((tries + 1))
      if [ $tries -ge 5 ]; then
        echo "FAIL"
        exit 1
      fi
      sleep 1
    done
    echo "done."
  ;;
  
  status)
    if running; then
      echo "$APP_NAME is running."
    else
      echo "$APP_NAME is NOT running."
    fi
  ;;

  restart)
    $0 stop
    sleep 2
    $0 start
  ;;

  *)
    echo "Usage: /etc/init.d/${APP_NAME} {start|stop|restart|status}"
    exit 1
  ;;
esac

exit 0
